name: firestore_ui
description: A port of firebase_database's FirebaseAnimatedList
version: 1.7.2
author: Gildásio Filho <gildasiogx@gmail.com>
homepage: https://github.com/gildaswise/firestore_ui

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  firebase_core: ^0.4.3+3
  cloud_firestore: ^0.13.0+1
  flutter_staggered_grid_view: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
